app = "recruitgo-arcade"
primary_region = "arn"

# HTTP service configuration for Node.js + Socket.IO
[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000  # Must match the port your app listens on
min_machines_running = 0
processes = [ "app" ]

# WebSockets are supported by default with [http_service]
# No extra config needed for Socket.IO

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"